name: Sync Repositories
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取完整的提交历史记录

      - name: Configure Git User
        run: |
          git config --global user.name "whn1281" # 设置提交者的姓名
          git config --global user.email "whn1281@126.com" # 设置提交者的电子邮件地址

      - name: Sync public code
        run: |
          git remote add destination https://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@github.com/whn1281/CloseSourceCode.git
          git push destination main:main --force
